### ISSUE TITLE
the experiment environment

### ISSUE THREAD

**Issue by mjqgit** [xzr12/PredCNN#1]
It is really an interesting work. could you list the experiment environment (e.g the operation system, graphics card...)? when I run the Moving MNIST  experiment (follow the hyper-parameters setting in the paper) on  a 2x 1080Ti, I found that the train time is so long (about 20 days). is it normal？

**Comment by xzr12** [comment]
> It is really an interesting work. could you list the experiment environment (e.g the operation system, graphics card...)? when I run the Moving MNIST experiment (follow the hyper-parameters setting in the paper) on a 2x 1080Ti, I found that the train time is so long (about 20 days). is it normal？

We use Ubuntu 16.04 with Nvidia Titan X graphics card, and still requires several iterations till convergence.

**Comment by xzr12** [comment]
We use Ubuntu 16.04 with Nvidia Titan X graphics card, and still requires several iterations till convergence.
