### ISSUE TITLE
Are you comparing to "VPN baseline" or "VPN"?

### ISSUE THREAD

**Issue by PharrellWANG** [xzr12/PredCNN#2]
@xzr12 
Hi Ziru, 

Thanks for your paper and code. 
After skimming your paper, I have a question: Are you comparing to "VPN baseline" or "VPN"?

Best,
Pharrell

**Comment by xzr12** [comment]
We compare our method with the VPN baseline and we've mentioned it in the experiment section.

**Comment by PharrellWANG** [comment]
Thanks for the reply. I see.

**Comment by PharrellWANG** [comment]
@xzr12 In experiment section: “Due to the difficulty of reproducing the experimental results of the VPN”

May I ask what exactly is the “difficulty” mentioned in the paper? (Insufficient GPU memory for 256 channels in convLSTM or prohibitive converging time for 19.2M training sequences? Or others?)

**Comment by xzr12** [comment]
> @xzr12 In experiment section: “Due to the difficulty of reproducing the experimental results of the VPN”
> 
> May I ask what exactly is the “difficulty” mentioned in the paper? (Insufficient GPU memory for 256 channels in convLSTM or prohibitive converging time for 19.2M training sequences? Or others?)

**Comment by xzr12** [comment]
The difficulty mentioned in the paper mainly lies in the reproduction of PixelCNN decoder so we adopt the baseline version of VPN.
